# Generated by Django 2.2.3 on 2019-07-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('maker', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('danger', models.TextField()),
            ],
        ),
    ]
