# Generated by Django 2.2.3 on 2019-08-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medihelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='price',
            new_name='score',
        ),
    ]
